[phases.setup]
nixPkgs = ["nodejs_18", "python310", "python310Packages.setuptools", "pkg-config", "cairo", "pango", "libjpeg", "giflib"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "npm start" 