[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pkg-config", "cairo", "pango", "libjpeg", "giflib"]

[phases.install]
cmds = ["npm ci", "npm rebuild sqlite3 --build-from-source"]

[start]
cmd = "npm start" 