[providers]
nodejs = "18"

[variables]
NODE_ENV = "production"

[phases.setup]
aptPkgs = ["build-essential", "python3", "python3-dev", "sqlite3", "libsqlite3-dev"]

[phases.build]
cmds = [
  "npm ci",
  "npm rebuild sqlite3 --build-from-source"
]

[start]
cmd = "npm start" 