[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pkg-config", "cairo", "pango", "libjpeg", "giflib"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run postinstall"]

[start]
cmd = "npm start" 